apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: default
spec:
  releaseName: metrics-server
  targetNamespace: kube-system
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 2.9.0
    name: metrics-server
  values:
    replicaCount: 1
# https://ftclausen.github.io/general/setting_up_k8s_with_metrics_server/ setup client crt and provide ca crt
    args: 
     - --kubelet-insecure-tls
     - --v=5
    rbac:
      pspEnabled: true