apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sops-secrets-operator
spec:
  releaseName: sops-secrets-operator
  chart:
    git: git@github.com:isindir/sops-secrets-operator
    path: chart/sops-secrets-operator
    ref: "master/0.0.9"
  values:
 