apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: filebeat
spec:
  releaseName: filebeat
  chart:
    repository: "https://helm.elastic.co"
    name: filebeat
    version: 7.6.0
  values:


