apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kiam-agent-certificate
spec:
  secretName: kiam-agent-certificate-secret
  issuerRef:
    name: self-signed-certificate-issuer
    kind: Issuer
  commonName: kiam-agent
  usages:
  - "any"
  dnsNames:
    - kiam-agent
  renewBefore: 360h 
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kiam-server-certificate
spec:
  secretName: kiam-server-certificate-secret
  issuerRef:
    name: self-signed-certificate-issuer
    kind: Issuer
  commonName: kiam-server
  usages:
  - "any"
  dnsNames:
    - kiam-server
    - localhost
  ipAddresses:
    - 127.0.0.1
  renewBefore: 360h 