apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kiam
spec:
  values:
    psp:
      create: true
    agent:
      log:
        level: debug
      extraEnv:
        - name: AWS_METADATA_SERVICE_TIMEOUT
          value: "8"
        - name: AWS_METADATA_SERVICE_NUM_ATTEMPTS
          value: "5"
      host:
        iptables: false
      tlsSecret: kiam-agent-certificate-secret
      tlsCerts:
        certFileName: tls.crt
        keyFileName: tls.key
        caFileName: ca.crt
    server:
      assumeRoleArn: "arn:aws:iam::769214547189:role/kiam-server"
      roleBaseArn: arn:aws:iam::769214547189:role/
      tlsSecret: kiam-server-certificate-secret
      useHostNetwork: true
      log:
        level: debug
      extraEnv:
        - name: AWS_METADATA_SERVICE_TIMEOUT
          value: "8"
        - name: AWS_METADATA_SERVICE_NUM_ATTEMPTS
          value: "5"
      tlsCerts:
        certFileName: tls.crt
        keyFileName: tls.key
        caFileName: ca.crt
    extraHostPathMounts:
      - name: ssl-certs
        mountPath: /etc/ssl/certs
        hostPath: /etc/ssl/certs #Debian kops path
        readOnly: true


      
        