apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kiam
spec:
  values:
    psp:
      create: true
    agent:
      log:
        level: debug
      extraEnv:
        - name: GRPC_GO_LOG_SEVERITY_LEVEL
          value: info
        - name: GRPC_GO_LOG_VERBOSITY_LEVEL
          value: 8
      host:
        iptables: true
      tlsSecret: kiam-agent-certificate-secret
      tlsCerts:
        certFileName: tls.crt
        keyFileName: tls.key
        caFileName: ca.crt
    server:
      assumeRoleArn: "arn:aws:iam::769214547189:role/nodes.kops.k8s.local"
      roleBaseArn: arn:aws:iam::769214547189:role/
      tlsSecret: kiam-server-certificate-secret
      log:
        level: debug
      extraEnv:
        - name: GRPC_GO_LOG_SEVERITY_LEVEL
          value: info
        - name: GRPC_GO_LOG_VERBOSITY_LEVEL
          value: 8
      tlsCerts:
        certFileName: tls.crt
        keyFileName: tls.key
        caFileName: ca.crt
    extraHostPathMounts:
      - name: ssl-certs
        mountPath: /etc/ssl/certs
        hostPath: /etc/ssl/certs #Debian kops path
        readOnly: true


      
        