apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kiam
spec:
  values:
    psp:
      create: true
    agent:
      log:
        level: debug
      extraEnv:
        - name: AWS_METADATA_SERVICE_TIMEOUT
          value: "8"
        - name: AWS_METADATA_SERVICE_NUM_ATTEMPTS
          value: "5"
      host:
        iptables: false
        interface: "cali+"
      tlsSecret: kiam-agent-certificate-secret
      tlsCerts:
        certFileName: tls.crt
        keyFileName: tls.key
        caFileName: ca.crt
    server:
      service:
        targetPort: 8443
      tolerations:
       - key: node-role.kubernetes.io/master
         effect: NoSchedule
      nodeSelector:
        kubernetes.io/role: master
      assumeRoleArn: "arn:aws:iam::769214547189:role/kiam-server"
      tlsSecret: kiam-server-certificate-secret
      sslCertHostPath: /usr/share/ca-certificates/mozilla
      useHostNetwork: true
      log:
        level: debug
      extraEnv:
        - name: AWS_METADATA_SERVICE_TIMEOUT
          value: "8"
        - name: AWS_METADATA_SERVICE_NUM_ATTEMPTS
          value: "5"
      tlsCerts:
        certFileName: tls.crt
        keyFileName: tls.key
        caFileName: ca.crt
    extraHostPathMounts:
      - name: ssl-certs
        mountPath: /etc/ssl/certs
        hostPath: /usr/share/ca-certificates/mozilla #Debian kops path
        readOnly: true


      
        