apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: root-ca-issuer
spec:
  selfSigned: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: root-ca-cert
spec:
  secretName: root-ca-cert
  commonName: root-ca-cert
  isCA: true
  issuerRef:
    name: root-ca-issuer
    kind: Issuer
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: self-signed-certificate-issuer
spec:
  ca:
    secretName: root-ca-cert