apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: root-ca-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: root-ca-cert
spec:
  secretName: root-ca-cert
  commonName: root-ca-cert
  # https://github.com/jetstack/cert-manager/issues/2407
  usages:
  - "any"
  isCA: true
  issuerRef:
    name: root-ca-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: self-signed-certificate-issuer
spec:
  ca:
    secretName: root-ca-cert