apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metricbeat
  namespace: logging
spec:
  releaseName: metricbeat
  chart:
    repository: "https://helm.elastic.co"
    name: metricbeat
    version: 7.6.0
  values: 
    metricbeatConfig:
      metricbeat.yml: |
        system:
          hostfs: /hostfs
        metricbeat.modules:
        - module: kubernetes
          enabled: true
          metricsets:
            - event
        output.elasticsearch:
          hosts: 
            - 'elasticsearch:9200'
          loadbalancer: true
          compression_level: 4
          protocol: http
          index: "k8s.metrics-%{+yyyy.MM.dd}"
        setup.ilm.enabled: false
        setup.template.enabled: true
        setup.template.name: "k8s"
        setup.template.pattern: "k8s.*"
        setup.template.overwrite: false
        setup.template.settings:
          index.number_of_shards: 1
          index.number_of_replicas: 1   