apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: opendistro-es
spec:
  releaseName: opendistro
  chart:
    git: git@github.com:opendistro-for-elasticsearch/opendistro-build.git
    path: "helm/opendistro-es"
    ref: "opendistro-1.5"
  values:

