apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: opendistro-es
spec:
  releaseName: opendistro-rnd
  chart:
    git: git@github.com:opendistro-for-elasticsearch/opendistro-build.git
    ref: "v0.10.0"
    path: "helm/opendistro-es"
  values:
    kibana:
      enabled: true
      image: amazon/opendistro-for-elasticsearch-kibana
      imageTag: 1.4.0
      replicas: 1
      port: 5601
      externalPort: 443
      resources: 
       limits:
         cpu: 2500m
         memory: 2Gi
       requests:
         cpu: 500m
         memory: 512Mi
    elasticsearch:
      image: amazon/opendistro-for-elasticsearch
      imageTag: 1.4.0
      master:
        enabled: true
        replicas: 1
        persistence:
          enabled: false
      data:
        enabled: true
        replicas: 1
        updateStrategy: "RollingUpdate"
        persistence:
          enabled: false
      client:
        enabled: false
        replicas: 1
