apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-inputs
  labels:
    k8s-app: filebeat
data:
  kubernetes.yml: |-
    - type: docker
      containers.ids:
      - "*"
      processors:
        - add_kubernetes_metadata:
            in_cluster: true
    output.elasticsearch:
      hosts:
        - 'elasticsearch:9200'
      loadbalancer: true
      compression_level: 4
      protocol: http
      index: "k8s.%{[kubernetes.namespace]}-%{+yyyy.MM.dd}"
    
    setup.ilm.enabled: false
    setup.template.enabled: true
    setup.template.name: "k8s"
    setup.template.pattern: "k8s.*"
    setup.template.overwrite: false
    setup.template.settings:
      index.number_of_shards: 1
      index.number_of_replicas: 1 