apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: opendistro-es
spec:
  releaseName: opendistro-rnd
  values:
    kibana:
      enabled: true
      image: amazon/opendistro-for-elasticsearch-kibana
      imageTag: 1.4.0
      replicas: 1
      port: 5601
      externalPort: 443
      resources: 
       limits:
         cpu: 2500m
         memory: 2Gi
       requests:
         cpu: 500m
         memory: 512Mi
    elasticsearch:
      image: amazon/opendistro-for-elasticsearch
      imageTag: 1.4.0
      master:
        enabled: true
        replicas: 1
        persistence:
          enabled: false
      data:
        enabled: true
        replicas: 1
        updateStrategy: "RollingUpdate"
        persistence:
          enabled: false
      client:
        enabled: true
        replicas: 1