apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: opendistro-es
spec:
  releaseName: opendistro-rnd
  values:
    kibana:
      imageTag: 1.4.0
      externalPort: 443
      resources: 
       limits:
         cpu: 2500m
         memory: 2Gi
       requests:
         cpu: 500m
         memory: 512Mi
    elasticsearch:
      imageTag: 1.4.0
      master:
        persistence:
          enabled: false
        resources: 
          limits:
            cpu: 1
            memory: 1024Mi
          requests:
            cpu: 200m
            memory: 1024Mi
      data:
        persistence:
          enabled: false
        resources: 
          limits:
            cpu: 1
            memory: 1024Mi
          requests:
            cpu: 200m
            memory: 1024Mi
      client:
        resources: 
          limits:
            cpu: 1
            memory: 1024Mi
          requests:
            cpu: 200m
            memory: 1024Mi
