apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  releaseName: cert-manager
  chart:
    git: git@github.com:jetstack/cert-manager
    path: deploy/charts/cert-manager
    ref: "release-0.13"
  values:
 