apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# wget https://raw.githubusercontent.com/jetstack/cert-manager/v0.13.1/deploy/manifests/00-crds.yaml 
- 00-crds.yaml
- helm_release.yaml
